services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  kafka-1:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 1
    networks:
      - kafka-net

  kafka-2:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka-2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 1
    networks:
      - kafka-net

  vehicle:
    image: python:3.9-slim
    container_name: vehicle
    depends_on:
      - kafka-1
      - kafka-2
    stdin_open: true    # <–– habilita stdin para input()
    tty: true           # <–– asigna un TTY para input()
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      bash -lc "pip install confluent-kafka && \
                 python3 producers/producer_camera.py \
                   --bootstrap-servers kafka-1:9092,kafka-2:9093"

    networks:
      - kafka-net

  digitaltwin:
    image: python:3.9-slim
    container_name: digitaltwin
    depends_on:
      - kafka-1
      - kafka-2
    volumes:
      - ./:/app
    working_dir: /app
    command: 
      - "bash"
      - "-lc"
      - |
        pip install confluent-kafka && \
        python3 consumers/consumer_camera.py --bootstrap-servers kafka-1:9092,kafka-2:9093
    networks:
      - kafka-net



networks:
  kafka-net:
    driver: bridge
